/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FeedbacksRouteImport } from './routes/feedbacks'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicSyncDiscordRouteImport } from './routes/api/public/sync-discord'

const FeedbacksRoute = FeedbacksRouteImport.update({
  id: '/feedbacks',
  path: '/feedbacks',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncDiscordRoute = ApiPublicSyncDiscordRouteImport.update({
  id: '/api/public/sync-discord',
  path: '/api/public/sync-discord',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/feedbacks': typeof FeedbacksRoute
  '/api/public/sync-discord': typeof ApiPublicSyncDiscordRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/feedbacks': typeof FeedbacksRoute
  '/api/public/sync-discord': typeof ApiPublicSyncDiscordRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/feedbacks': typeof FeedbacksRoute
  '/api/public/sync-discord': typeof ApiPublicSyncDiscordRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/feedbacks' | '/api/public/sync-discord'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/feedbacks' | '/api/public/sync-discord'
  id: '__root__' | '/' | '/admin' | '/feedbacks' | '/api/public/sync-discord'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  FeedbacksRoute: typeof FeedbacksRoute
  ApiPublicSyncDiscordRoute: typeof ApiPublicSyncDiscordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/feedbacks': {
      id: '/feedbacks'
      path: '/feedbacks'
      fullPath: '/feedbacks'
      preLoaderRoute: typeof FeedbacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync-discord': {
      id: '/api/public/sync-discord'
      path: '/api/public/sync-discord'
      fullPath: '/api/public/sync-discord'
      preLoaderRoute: typeof ApiPublicSyncDiscordRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  FeedbacksRoute: FeedbacksRoute,
  ApiPublicSyncDiscordRoute: ApiPublicSyncDiscordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
